Release/invoice
fpiemontesi/fernorte-app-2w1 pull request #26
Opened 2023-10-18 22:53 UTC by 113949-Galindo-Maximo

Cree el componente delete factura e hice el html con boostrap

2023-10-18 23:27 UTC, fpiemontesi requested changes
Veo que hiciste un fork del repo lo cual no era lo que se definió a la hora de trabajar. Recordá que deberías trabjar con ramas de este mismo repositorio y luego mergear siempre en la rama release/invoice en tu caso. Cualquier duda que tengas me la consultas.

2023-10-19 15:49 UTC, 113949-Galindo-Maximo commented
Profe no entiendo xq no me autorizó el push. Si bien cree una rama lo hice xq se generaria conflictos con mis compañeros de equipo

2023-10-19 15:49 UTC, 113949-Galindo-Maximo commented
Que debo hacer para que me lo autorice

2023-10-19 16:08 UTC, fpiemontesi commented
> Profe no entiendo xq no me autorizó el push. Si bien cree una rama lo hice xq se generaria conflictos con mis compañeros de equipo

En el comentario que te dejé arriba dice por que no lo aprobé. El problema es que vos hiciste un fork de este repositorio y ahi creaste una rama y e hiciste el merge a este repositorio. Lo que se solicitó es que crees una rama desde este mismo repositorio (no hace falta hacer un fork) y desde esa rama una vez que hayas hecho tus cambios los subis y luego creas el pull request a la rama correspondiente. 

Por ende el proceso que deberías seguir es:
- Bajar este repositorio (https://github.com/fpiemontesi/fernorte-app-2w1)
- Crear tu rama en base a la rama de release que se corresponda con el equipo al que perteneces.
- Realizar los cambios
- Commit y Push
- Crear el Pull Request a la rama desde donde saliste

Si no quedó claro decime y te lo explico de nuevo o vemos de organizar una reunión para sacarte las dudas.

2023-10-19 16:16 UTC, 113949-Galindo-Maximo commented
Eso hice, cree la rama delete factura y la fusione con release/invoice. Lo que estuvo mal fue pedir el pull request a este repositorio?

2023-10-19 16:18 UTC, 113949-Galindo-Maximo commented
El problema esq no veo mis cambios en el repositorio

2023-10-19 18:03 UTC, closed without merging

2023-10-19 18:05 UTC, 113949-Galindo-Maximo commented
Ahi estuve intentando lo que usted dijo. Parece ser que no tenemos permiso nisiquiera para hacer el pull request. Cree la rama desde release/invoice

2023-10-19 18:47 UTC, fpiemontesi commented
> 113949-Galindo-Maximo

Ahi verifiqué y no estabas agregado como colaborador... seguramente no aceptaste la petición a tiempo y se te venció. Ya estás agregado como colaborador asi que ahora deberías tener permisos para crear ramas/pull request y todo lo demas... Avisame cualquier cosa.