Compras/crud proveedores
fpiemontesi/fernorte-app-2w1 pull request #44
Opened 2023-10-21 20:43 UTC by 110899-SarateLuciana-2w1

2023-10-29 00:09 UTC, fpiemontesi commented
Se hizo el merge a la rama main cuando en realidad debería haber sido a la rama release/purchases

2023-10-29 00:16 UTC, fpiemontesi requested changes

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.html
> +            <option selected>Open this select menu</option>
Estos valores son incorrectos. Además deberían estar en un listado en el typescript y aquí utilizar un ngFor. Incluso podrían hasta venir desde una API si ya lo tienen planificado en algun sprint.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.html
> +            <option selected>--Seleccione uno--</option>
Estos valores son incorrectos. Además deberían estar en un listado en el typescript y aquí utilizar un ngFor. Incluso podrían hasta venir desde una API si ya lo tienen planificado en algun sprint.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.html
> +            <option value="1">-</option>
Estos valores son incorrectos. Además deberían estar en un listado en el typescript y aquí utilizar un ngFor. Incluso podrían hasta venir desde una API si ya lo tienen planificado en algun sprint.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.html
> +          <select class="form-select" aria-label="Default select example">
Esto podría ser una caja de texto para que no tengan que generar una base de datos gigante con esta información... Si ya la tienen desarrollada deberían consumir un servicio para llenar este combo.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.html
> +            <option selected>--Seleccione uno--</option>
Estos valores son incorrectos. Además deberían estar en un listado en el typescript y aquí utilizar un ngFor. Incluso podrían hasta venir desde una API si ya lo tienen planificado en algun sprint.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.ts
> +    console.log('Proveedor cargado:', this.proveedor);
Podrían haber hecho la integración con un servidor json con información mockeada. https://www.npmjs.com/package/json-server

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-componenteditar/modal-componenteditar.component.html
Aplica lo mismo que el formulario de alta.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-componenteditar/modal-componenteditar.component.ts
Aplica lo mismo que el formulario de alta.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/proveedores/proveedores.component.html
> +    <button class="button btn btn-primary" (click)="openModalAlta()">Nuevo</button>
Podrían utilizar bootstrap icons. https://icons.getbootstrap.com/

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-component/modal-component.component.ts
> +export class ModalComponentComponent {
Este componente podría ser mejor nombrado para representar lo que realmente hace. Evitar poner dos veces Component ya que es repetitivo.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-componentbaja/modal-componentbaja.component.ts
> +export class ModalComponentbajaComponent {
Evitar utilizar Component en los nombres de los componentes ya que angular lo agrega solo. Baja debería comenzar con mayuscula.

2023-10-29 00:16 UTC, fpiemontesi commented on src/app/modules/purchase/components/modal-componenteditar/modal-componenteditar.component.ts
> +export class ModalComponenteditarComponent {
Evitar utilizar Component en los nombres de los componentes ya que angular lo agrega solo. Editar debería comenzar con mayuscula.

2023-11-03 14:19 UTC, fpiemontesi requested changes

2023-11-03 14:19 UTC, fpiemontesi commented on src/app/app.component.ts
> +  title(title: any) {
Que es esto?

2023-11-03 14:19 UTC, fpiemontesi commented on .gitignore
> +/.vs
Los archivos dentro de la carpeta .vs que se agregaron no deberían ser subidos al repo. Para ignorarlo hay que poner en el gitignore `.vs/`

2023-11-03 14:19 UTC, fpiemontesi commented on src/app/modules/purchase/components/navbar/item-navbar/item-navbar.component.css
Por lo que veo se copiaron todos los estilos de Bootstrap lo cual es incorrecto ya que bootstrap está importado en el proyecto y esto puede provocar errores además de ser innecesario. Por favor solo agreguen los estilos que necesitan para este componente.

2023-11-03 14:19 UTC, fpiemontesi commented on src/app/modules/purchase/components/navbar/navbar.component.css
Por lo que veo se copiaron todos los estilos de Bootstrap lo cual es incorrecto ya que bootstrap está importado en el proyecto y esto puede provocar errores además de ser innecesario. Por favor solo agreguen los estilos que necesitan para este componente.

2023-11-08 02:37 UTC, 110989JonathanAybar commented on src/app/app.component.ts
> +  title(title: any) {
esto se genero automacticamente. ya se va a corregir

2023-11-08 02:38 UTC, 110989JonathanAybar commented on .gitignore
> +/.vs
esta carpetas se agregaron porque por no se agrego la exclusión de la carpeta en el .gitignore. Ya se va a corregir.

2023-11-08 23:40 UTC, 110899-SarateLuciana-2w1 commented
Profe el error no se pudo solucionar, vamos a subir otra rama.

2023-11-09 21:42 UTC, closed without merging