Feature/registrar lote
fpiemontesi/fernorte-app-2w1 pull request #46
Opened 2023-10-22 21:59 UTC by 114007-Bima-Santiago

desarrollo de la interfaz para registrar un lote

2023-10-29 22:50 UTC, fpiemontesi requested changes

2023-10-29 22:50 UTC, fpiemontesi commented on src/app/modules/inventory/components/registrar-lotes/registrar-lotes.component.ts
> +  existences: Existence[]= [];
No mezclen los idiomas. Si las clases están nombradas en ingles, lo mismo tendría que pasar con las variables para mantener una consistencia en nuestra aplicacion.

2023-10-29 22:50 UTC, fpiemontesi commented on src/app/modules/inventory/components/registrar-lotes/registrar-lotes.component.ts
> +export class RegistrarLotesComponent {
Agregar las interfaces de los hooks utilizados: `OnInit` `OnDestroy` etc

2023-10-29 22:50 UTC, fpiemontesi commented on src/app/modules/inventory/components/registrar-lotes/registrar-lotes.component.ts
> +  crear(){
Los nombres de los metodos tambien tienen que estar en ingles

2023-10-29 22:50 UTC, fpiemontesi commented on src/app/modules/inventory/components/registrar-lotes/registrar-lotes.component.ts
> +      alert("Ya existe un lote en la misma seccion y estantería, no entra otro");
Para los mensajes al usuario deberían utilizar el componente Toast de Bootstrap.

2023-10-29 22:50 UTC, fpiemontesi commented on src/app/modules/inventory/inventory.module.ts
> +    FormsModule
Este modulo ya está importado en el modulo raiz por ende no es necesario importarlo nuevamente.

2023-10-29 22:50 UTC, fpiemontesi commented on src/app/modules/inventory/models/existence.ts
> +  minimun_stock:number = 0;
Los nombres de las propiedades de las clases/interfaces tienen que estar en camelCase. En caso de tener que transformarlos desde un Observable pueden hacerlo utilizando la libreria rxjs por medio de la funcion map. https://rxjs.dev/api/operators/map

Esto aplica para todas las interfaces/clases que hayan desarrollado.

2023-10-31 20:21 UTC, 114007-Bima-Santiago commented on src/app/modules/inventory/components/registrar-lotes/registrar-lotes.component.ts
> +      alert("Ya existe un lote en la misma seccion y estantería, no entra otro");
No puedo eliminar el import de FormsModule, me da error el ngModel

2023-11-09 11:20 UTC, fpiemontesi approved these changes

2023-11-15 21:19 UTC, merged