Inventory/registrar remito
fpiemontesi/fernorte-app-2w1 pull request #59
Opened 2023-10-26 00:49 UTC by MartinMacielBramoso

New pull request (canceled the previous one). Added function "Registrar remito" to inventory module

2023-10-29 22:56 UTC, fpiemontesi requested changes

2023-10-29 22:56 UTC, fpiemontesi commented on src/app/modules/inventory/components/remito/registrar-remito/registrar-remito.component.html
> +                  <button class="btn btn-danger" (click)="eliminarDetalle(i)">X</button>
Deberían cambiar este boton por un unico de la libreria de bootstrap que ya se encuentra disponible en las ramas de release. https://icons.getbootstrap.com/

2023-10-29 22:56 UTC, fpiemontesi commented on src/app/modules/inventory/components/remito/registrar-remito/registrar-remito.component.ts
> +      this.detalle = new DetalleRemito();
Falta la llamada a la API? Por lo menos se podría agregar la llamada al servicio y que ese servicio haga la llamada por medio de json-server. https://www.npmjs.com/package/json-server

2023-10-29 22:56 UTC, fpiemontesi commented on src/app/modules/inventory/inventory.module.ts
> +  imports: [CommonModule, FormsModule],
No hace falta importar el FormsModule ya que se encuentra importado en el modulo raiz.

2023-10-29 22:56 UTC, fpiemontesi commented on src/app/modules/inventory/models/DetalleRemito.ts
> +export class DetalleRemito {
No se usa snake case para los nombres de los archivos. Generalmente se utiliza lo mismo que propone Angular, es decir, kebab-case o dashe-case para los archivos y para el codigo en los componentes camelCase.

Esto aplica para todas las clases/interfaces que tengas en la aplicacion y futuros Pull Requests.

2023-10-29 23:50 UTC, MartinMacielBramoso commented on src/app/modules/inventory/components/remito/registrar-remito/registrar-remito.component.ts
> +      this.detalle = new DetalleRemito();
Tengo permiso para usar el comando "npm i json-server"?

2023-10-31 02:58 UTC, MartinMacielBramoso commented on src/app/modules/inventory/inventory.module.ts
> +  imports: [CommonModule, FormsModule],
Sin el import aquí no funciona el html, el import del modulo raiz parece que no lo utiliza o no lo toma.

2023-11-09 11:07 UTC, fpiemontesi approved these changes

2023-11-09 11:20 UTC, fpiemontesi approved these changes

2023-11-15 21:58 UTC, merged